# MOVIE RECOMMENDATION
GOAL:: Based on given features movies should be recommended to the person based on content and popularity

In [12]:
#importing dependencies

import numpy as np
import pandas as pd
import difflib #to recommend movies to the user which has to be the close match to the name he has given even though with some errors.
from sklearn.feature_extraction.text import TfidfVectorizer #Used to convert object type data to meaningful feature vectors called numerical data
from sklearn.metrics.pairwise import cosine_similarity #it will give similarity score for all the movies with the given movie name and also to recognize all the higest similarity score movies inorder to recommend to the user

# Data pre-processing

In [13]:
# loading the data into the pandas dataframe

movies_data = pd.read_csv('movies.csv')

In [14]:
# viewing first fiverows of the dataframe

movies_data.head()

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   148.0   
3  Following the death of District Attorney Harve...  112.312950  ...   165.0   
4  John Carter is a war-weary, former military ca...   43.926995  ...   132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski  
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes  
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan  
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton  

[5 rows x 24 columns]

In [15]:
#viewing rows and columns of the data frame

movies_data.shape

(4803, 24)

In [16]:
# Viewing column names

movies_data.columns

Index(['index', 'budget', 'genres', 'homepage', 'id', 'keywords',
       'original_language', 'original_title', 'overview', 'popularity',
       'production_companies', 'production_countries', 'release_date',
       'revenue', 'runtime', 'spoken_languages', 'status', 'tagline', 'title',
       'vote_average', 'vote_count', 'cast', 'crew', 'director'],
      dtype='object')

In [17]:
# feature selection for recommendation

required_features = ['genres', 'keywords', 'tagline', 'cast', 'director', 'overview']
required_features

['genres', 'keywords', 'tagline', 'cast', 'director', 'overview']

In [18]:
#Checking for null values

movies_data.isnull().sum()

index                      0
budget                     0
genres                    28
homepage                3091
id                         0
keywords                 412
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
cast                      43
crew                       0
director                  30
dtype: int64

In [19]:
#Replacing null values with empty string

for feature in required_features:
    movies_data[feature] = movies_data[feature].fillna('')

In [20]:
# combining all required features

combined_features = movies_data['genres'] + movies_data['keywords'] + movies_data['tagline']+ movies_data['cast'] + movies_data['director'] + movies_data['overview'] 

In [21]:
combined_features

0       Action Adventure Fantasy Science Fictioncultur...
1       Adventure Fantasy Actionocean drug abuse exoti...
2       Action Adventure Crimespy based on novel secre...
3       Action Crime Drama Thrillerdc comics crime fig...
4       Action Adventure Science Fictionbased on novel...
                              ...                        
4798    Action Crime Thrillerunited states\u2013mexico...
4799    Comedy RomanceA newlywed couple's honeymoon is...
4800    Comedy Drama Romance TV Moviedate love at firs...
4801    A New Yorker in ShanghaiDaniel Henney Eliza Co...
4802    Documentaryobsession camcorder crush dream gir...
Length: 4803, dtype: object

# Feature Extraction

In [22]:
# converting the required features data into the feature vectors 
# with numerical data we can easily find the cosine similarity data

vectorizer = TfidfVectorizer()




In [23]:
#Fitting vectors into the object

vectors = vectorizer.fit_transform(combined_features)

In [24]:
print(vectors)

  (0, 7211)	0.15785649032038593
  (0, 1428)	0.11989857008807574
  (0, 1729)	0.05218744162287104
  (0, 31503)	0.16246949894069793
  (0, 1767)	0.03029299085900534
  (0, 29053)	0.15399515630559496
  (0, 15616)	0.1375264729723761
  (0, 4070)	0.09485675276006127
  (0, 40265)	0.14002976378399234
  (0, 3685)	0.09296257980287868
  (0, 5664)	0.05874061446709645
  (0, 26678)	0.10488796921224784
  (0, 41643)	0.14686488493102665
  (0, 28923)	0.0470169768892924
  (0, 26966)	0.1460008156074791
  (0, 40135)	0.02943613143327801
  (0, 11221)	0.1757655714895802
  (0, 21025)	0.039545466180595595
  (0, 25249)	0.13812800605810213
  (0, 29605)	0.19223425482279902
  (0, 6545)	0.12047111075071086
  (0, 256)	0.18693252297203264
  (0, 5877)	0.19906937596983335
  (0, 33610)	0.2087029381560179
  (0, 26349)	0.1182593486000071
  :	:
  (4802, 40777)	0.08561045088611684
  (4802, 39396)	0.06943049448630909
  (4802, 28551)	0.06678960321620862
  (4802, 17909)	0.08507855285433547
  (4802, 43146)	0.08406102416253504
  (48

## Similarity Scores

In [25]:
# obtaining similarity score using cosine similarity

score = cosine_similarity(vectors)

In [26]:
print(score)

[[1.         0.04633911 0.02108447 ... 0.02546564 0.03220701 0.0067216 ]
 [0.04633911 1.         0.03935666 ... 0.04621248 0.03190481 0.01639624]
 [0.02108447 0.03935666 1.         ... 0.0256327  0.0119989  0.01472549]
 ...
 [0.02546564 0.04621248 0.0256327  ... 1.         0.03888249 0.02053173]
 [0.03220701 0.03190481 0.0119989  ... 0.03888249 1.         0.03414082]
 [0.0067216  0.01639624 0.01472549 ... 0.02053173 0.03414082 1.        ]]


In [27]:
score.shape

(4803, 4803)

In [37]:
#user given movie 

movie = input("Enter a movie name: ")

Enter a movie name: Old guard


In [38]:
# creating a list of movies present in data

list_titles = movies_data['title'].tolist()



In [39]:
list_titles

['Avatar',
 "Pirates of the Caribbean: At World's End",
 'Spectre',
 'The Dark Knight Rises',
 'John Carter',
 'Spider-Man 3',
 'Tangled',
 'Avengers: Age of Ultron',
 'Harry Potter and the Half-Blood Prince',
 'Batman v Superman: Dawn of Justice',
 'Superman Returns',
 'Quantum of Solace',
 "Pirates of the Caribbean: Dead Man's Chest",
 'The Lone Ranger',
 'Man of Steel',
 'The Chronicles of Narnia: Prince Caspian',
 'The Avengers',
 'Pirates of the Caribbean: On Stranger Tides',
 'Men in Black 3',
 'The Hobbit: The Battle of the Five Armies',
 'The Amazing Spider-Man',
 'Robin Hood',
 'The Hobbit: The Desolation of Smaug',
 'The Golden Compass',
 'King Kong',
 'Titanic',
 'Captain America: Civil War',
 'Battleship',
 'Jurassic World',
 'Skyfall',
 'Spider-Man 2',
 'Iron Man 3',
 'Alice in Wonderland',
 'X-Men: The Last Stand',
 'Monsters University',
 'Transformers: Revenge of the Fallen',
 'Transformers: Age of Extinction',
 'Oz: The Great and Powerful',
 'The Amazing Spider-Man 2',

In [46]:
# Selecting closet movie name from our data  to recommend to the user

close_match = difflib.get_close_matches(movie, list_titles)
print(closest_match)

Wild Card


In [41]:
closest_match = close_match[0]
print(closest_match)

Wild Card


In [42]:
# finding the index of the movie

movie_index = movies_data[movies_data.title == closest_match]['index'].values[0]
print(movie_index)

1674


In [43]:
# getting a list of similar movies

similarity_score = list(enumerate(score[movie_index]))
print(similarity_score)

[(0, 0.004255806802319732), (1, 0.04159069671425114), (2, 0.006382941280938453), (3, 0.035269515679315244), (4, 0.018857758265431873), (5, 0.04481748581073284), (6, 0.02352169051622064), (7, 0.01866691154303901), (8, 0.01340927774265801), (9, 0.03931072454612383), (10, 0.019493408015726337), (11, 0.013808827333136351), (12, 0.01115530682870605), (13, 0.017670800497083503), (14, 0.051362983091364334), (15, 0.020528330844784476), (16, 0.007618192579076), (17, 0.05335643592493232), (18, 0.04046322351347839), (19, 0.012987528233497352), (20, 0.02184520765171152), (21, 0.02090103800568179), (22, 0.024752008764803244), (23, 0.007552672651897025), (24, 0.009553778435630569), (25, 0.022798035233304755), (26, 0.02711078307602531), (27, 0.019565941063416803), (28, 0.0006722924960004086), (29, 0.05083279781197809), (30, 0.02469823409435852), (31, 0.0077492378941880855), (32, 0.03304285155409148), (33, 0.003540587916998833), (34, 0.0038683313802544595), (35, 0.014413553142266866), (36, 0.021017215

In [44]:
# sorting based on similaroty score

sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True)

sorted_similar_movies

[(1674, 1.0000000000000004),
 (3476, 0.15727000237154942),
 (3291, 0.12762308572751013),
 (2084, 0.11637338202310231),
 (388, 0.11367555951398299),
 (1712, 0.11343853856672818),
 (3140, 0.11117265832631255),
 (1817, 0.10972528825040216),
 (2940, 0.10664688853383439),
 (1513, 0.10634796515668156),
 (3874, 0.10065202707830839),
 (3409, 0.0979492783078558),
 (2412, 0.09680654254516266),
 (1884, 0.09530822622556297),
 (724, 0.0935274085790032),
 (892, 0.09317120373900585),
 (1660, 0.09288298953615633),
 (1310, 0.09150004798196623),
 (1183, 0.0905518262277837),
 (2959, 0.08429020415896109),
 (1254, 0.08142457428171093),
 (2343, 0.07823870895713454),
 (446, 0.07770137360553575),
 (3526, 0.07708297625004938),
 (3048, 0.07706413230275522),
 (3956, 0.07681988856014459),
 (427, 0.07606259890005719),
 (4494, 0.07533556693632014),
 (1434, 0.07470050622794423),
 (3856, 0.07413145960304558),
 (1416, 0.07331506191810715),
 (4526, 0.0732987603390808),
 (3902, 0.07213672130444726),
 (2640, 0.0718293000

## Recommendation

In [45]:
# recommending top 10 movies

print("top10_recommended_movies")

i = 1
for movie in sorted_similar_movies:
    index = movie[0]
    title_from_index = movies_data[movies_data.index == index]['title'].values[0]
    if (i<11):
        print(i, title_from_index)
        i+=1
 

top10_recommended_movies
1 Wild Card
2 City Island
3 Pathology
4 eXistenZ
5 Ocean's Eleven
6 Last Vegas
7 The Lost City
8 The Bodyguard
9 Tomcats
10 Transporter 2
